# Generated by Django 4.1.3 on 2023-05-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_amount',
            field=models.IntegerField(default=0),
        ),
    ]
