# Generated by Django 4.1.3 on 2023-05-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0007_post_likes_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
